schemaVersion: 2.0.0

commandTests:
  - name: "awsiammapper installed"
    setup: []
    command: "python"
    args: ["-m", "pip", "freeze", "|", "grep", "awsiammapper"]
    expectedOutput: ["awsiammapper"]
  - name: "awsiammapper executable"
    setup: []
    command: "python"
    args: ["-m", "awsiammapper", "-h"]
    expectedOutput: [""]
  - name: "non-root executable"
    setup: []
    command: "python"
    args: ["-m", "awsiammapper", "-h"]
    expectedOutput: [""]
metadataTest:
  exposedPorts: []
  volumes: []
  entrypoint:  ["python3", "-m", "awsiammapper"]
  cmd: ["-h"]
  user: "awsiammapper"